steps:
- name: 'sglahn/platformio-core:3.6.0'  
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://drone-firmwares/$TAG_NAME'
    paths: ['/workspace/.pioenvs/esp8266/droneAir_firmware.bin']
