steps:
- name: 'sglahn/platformio-core:3.6.0'  
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://droneair-firmwares/$TAG_NAME'
    paths: ['/workspace/.pioenvs/esp8266/droneair_firmware.bin']
