steps:
  - name: python
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install --upgrade platformio
        pio run
    dir: .
artifacts:
  objects:
    location: 'gs://drone-firmwares/$REPO_NAME/$TAG_NAME'
    paths:
      - /workspace/.pio/build/$REPO_NAME/firmware.bin
