steps:
  - name: python
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install --upgrade platformio
        pio run
    dir: .
artifacts:
  objects:
    location: 'gs://drone-firmwares/$TAG_NAME'
    paths:
      - /workspace/.pio/build/esp8266/droneSoil_firmware.bin
